import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,realpathSync,rmSync,mkdirSync,writeFileSync,readFileSync,chmodSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {exportBundle,verifyBundle} from '../src/protocol/bundle.ts';
import {Ledger} from '../src/harness/ledger.ts';
import {Runner} from '../src/harness/runner.ts';
import {canonical,digest,fileDigest,readJson} from '../src/protocol/files.ts';

function fixture(){
 const root=realpathSync(mkdtempSync(join(tmpdir(),'photocraft-recovery-revision-')));const ledger=new Ledger(join(root,'state'));const task=ledger.create({idempotencyKey:'original',brief:'修复保存后的标题',plan:{document:{width:64,height:64},operations:[]},output:join(root,'failed'),authorization:{ref:'user',writeRoot:root,objects:[7]},budget:{deadline:Date.now()+60000,maxRevisions:1,reserveBytes:0}});const epoch=ledger.claim(task.id);ledger.transition(task.id,epoch,'reconciling');
 const skill=join(root,'skill');mkdirSync(join(skill,'scripts'),{recursive:true});mkdirSync(join(skill,'references'));writeFileSync(join(skill,'scripts/runtime.lock.json'),JSON.stringify({artifacts:{'darwin-arm64':{binarySha256:'9'.repeat(64)}}}));const runner=new Runner(ledger,{skillRoot:skill,python:'python3'});
 const checkpoint={recordSha256:'a'.repeat(64),projectSha256:'b'.repeat(64),origin:{planSha256:digest(canonical(task.request.plan))},nativeDocument:{layers:[{id:7,kind:'Type',text:{text:'ORIGINAL',font:'Arial',sizePt:10}}]}};
 ledger.update(task.id,epoch,current=>{current.checkpoint=checkpoint;current.executionIdentity=runner.identity();});
 const proposal={baseProjectSha256:checkpoint.projectSha256,checkpointRecordSha256:checkpoint.recordSha256,authorizationRef:'user',reason:'保存已核对，显式修复标题',operations:[{command:'type.edit',params:{layer:7,text:'RECOVERED'}}]};
 return {root,ledger,runner,task,proposal,close(){ledger.close();rmSync(root,{recursive:true,force:true});}};
}
test('checkpoint revision cannot dispatch from merely observed process disappearance',async()=>{const f=fixture();try{await assert.rejects(()=>f.runner.recover(f.task.id,f.proposal),/worker_resolution_required/);assert.equal(f.ledger.status(f.task.id).revisions,0);assert.equal(f.ledger.db.prepare('SELECT COUNT(*) AS n FROM tasks').get().n,1);}finally{f.close();}});
test('checkpoint request cannot be created without an original parent task',()=>{const f=fixture();try{assert.throws(()=>f.ledger.create({...f.task.request,idempotencyKey:'bypass',checkpoint:{output:f.task.request.output,recordSha256:'a'.repeat(64),planSha256:'c'.repeat(64),projectSha256:'b'.repeat(64)}}),/checkpoint_requires_revision/);}finally{f.close();}});

test('native checkpoint recovery binds a child, retains intent and budget, and does not replay unknown edits',{skip:process.env.PHOTOCRAFT_NATIVE_TEST!=='1'},async()=>{
 const root=realpathSync(mkdtempSync(join(tmpdir(),'photocraft-native-checkpoint-recovery-')));const ledger=new Ledger(join(root,'state'));
 try{
  const skillRoot=process.env.PHOTOCRAFT_SKILL_ROOT!;const sourceRoot=process.env.PHOTOCRAFT_SOURCE_ROOT!;const realPython=process.env.PHOTOCRAFT_PYTHON??'/opt/anaconda3/bin/python3';const shim=join(root,'python-shim');
  const injection=join(sourceRoot,'tests/fixtures/workflow_protocol_injection.py'),proxy=join(sourceRoot,'tests/fixtures/protocol_proxy.py');
  writeFileSync(shim,'#!'+realPython+'\nimport os,sys,runpy\nargs=sys.argv[1:]\nif len(args)>2 and args[2].endswith("workflow.py") and "--check" not in args and "--checkpoint" not in args:\n sys.argv=['+JSON.stringify(injection)+','+JSON.stringify(proxy)+',"malformed",'+JSON.stringify(join(root,'saves.jsonl'))+','+JSON.stringify(join(root,'capture.pcraft'))+','+JSON.stringify(join(root,'reply.json'))+',*args[2:]]\n runpy.run_path('+JSON.stringify(injection)+',run_name="__main__")\nelse:os.execv('+JSON.stringify(realPython)+',['+JSON.stringify(realPython)+',*args])\n');chmodSync(shim,0o700);
  const runner=new Runner(ledger,{skillRoot,python:shim});const task=ledger.create({idempotencyKey:'native-original',brief:'恢复保存后的标题，不复制图层',plan:{document:{width:64,height:64,background:'#ffffff'},operations:[{command:'type.create',params:{text:'ORIGINAL',font:'Arial',size:10,x:4,y:20},as:'title'}],exports:[{format:'png'}]},output:join(root,'failed'),authorization:{ref:'user',writeRoot:root},budget:{deadline:Date.now()+120000,maxRevisions:1,reserveBytes:1024}});
  const failed=await runner.run(task.id);assert.equal(failed.state,'reconciling');assert.equal(failed.technical.status,'NOT_RUN');assert.equal(failed.worker.processGroupGone,true);
  const checked=await runner.reconcile(task.id);assert.ok(checked.checkpoint?.origin,JSON.stringify(checked));const stage=checked.checkpoint.stage;const retained=Object.fromEntries(Object.keys(checked.checkpoint.files).map(name=>[name,fileDigest(join(stage,name))]));
  const context=readJson(join(stage,'recovery-context.json'));const layer=context.bindings.title.layer;
  const contextPath=join(stage,'recovery-context.json'),rootRecord=join(task.request.output,'failure.json'),stageRecord=join(stage,'failure.json');const originalContext=readFileSync(contextPath),originalRecord=readFileSync(rootRecord);
  const foreignContext=readJson(contextPath);foreignContext.taskBinding.workerToken='another-task-token';writeFileSync(contextPath,canonical(foreignContext));const foreignRecord=readJson(rootRecord);foreignRecord.files['recovery-context.json']={sha256:fileDigest(contextPath),bytes:readFileSync(contextPath).length};for(const path of [rootRecord,stageRecord])writeFileSync(path,canonical(foreignRecord));
  const foreign=await runner.reconcile(task.id);assert.equal(foreign.checkpoint,undefined);assert.match(foreign.reconcileError,/checkpoint_task_binding_mismatch/);assert.equal(foreign.technical.status,'NOT_RUN');writeFileSync(contextPath,originalContext);for(const path of [rootRecord,stageRecord])writeFileSync(path,originalRecord);assert.ok((await runner.reconcile(task.id)).checkpoint);

  const proposal={baseProjectSha256:checked.checkpoint.projectSha256,checkpointRecordSha256:checked.checkpoint.recordSha256,authorizationRef:'user',reason:'原保存已核对，修复现有标题',operations:[{command:'type.edit',params:{layer,text:'RECOVERED'}}]};
  // 各次拒绝不得预留修订预算或产生新任务。
  for(const bad of [{...proposal,authorizationRef:'other'},{...proposal,checkpointRecordSha256:'a'.repeat(64)},{...proposal,operations:[{command:'type.create',params:{text:'REPLAY'}}]},{...proposal,operations:[{command:'type.edit',params:{layer,text:'ORIGINAL'}}]}]){await assert.rejects(()=>runner.recover(task.id,bad));assert.equal(ledger.status(task.id).revisions,0);}
  const token=ledger.status(task.id).worker.token;ledger.update(task.id,checked.epoch,current=>{current.worker.token='foreign';});await assert.rejects(()=>runner.recover(task.id,proposal),/worker_receipt_identity_mismatch/);ledger.update(task.id,checked.epoch,current=>{current.worker.token=token;current.revisions=1;});await assert.rejects(()=>runner.recover(task.id,proposal),/budget_exhausted/);ledger.update(task.id,checked.epoch,current=>{current.revisions=0;});
  const child=await runner.recover(task.id,proposal);assert.equal(child.request.parentTask,task.id);assert.equal(child.request.checkpoint.recordSha256,checked.checkpoint.recordSha256);assert.equal(child.request.budget.deadline,task.request.budget.deadline);assert.equal(child.request.budget.maxRevisions,0);assert.equal(ledger.status(task.id).revisions,1);
  assert.equal((await runner.recover(task.id,proposal)).id,child.id);await assert.rejects(()=>runner.run(task.id),/reconcile_required/);
  const retainedProject=readFileSync(join(stage,'project.pcraft'));writeFileSync(join(stage,'project.pcraft'),'external modification');await assert.rejects(()=>runner.run(child.id));assert.equal(ledger.status(child.id).attempted,false);writeFileSync(join(stage,'project.pcraft'),retainedProject);
  const result=await runner.run(child.id);assert.equal(result.technical.status,'PASS',JSON.stringify(result));assert.equal(result.creative.status,'NOT_RUN');assert.equal(result.artifact.producerTaskId,child.id);assert.ok(result.artifact.sourceRefs.some(ref=>ref.assetId==='photocraft-checkpoint:'+task.id && ref.sha256===checked.checkpoint.projectSha256));
  const bundle=exportBundle(result,join(root,'bundle'));const bundled=verifyBundle(join(root,'bundle'),bundle.bundleSha256);assert.equal(bundled.lineage,'VERIFIED');assert.ok(bundled.artifact.sourceRefs.some(ref=>ref.assetId==='photocraft-checkpoint:'+task.id));
  const native=readJson(join(child.request.output,'native.json'));const layers:any[]=[];const walk=(rows:any[])=>{for(const row of rows){layers.push(row);if(row.children)walk(row.children);}};walk(native.layers);assert.equal(layers.filter(row=>row.kind==='Type').length,1);assert.equal(layers.find(row=>row.id===layer).text.text,'RECOVERED');
  assert.deepEqual(Object.fromEntries(Object.keys(retained).map(name=>[name,fileDigest(join(stage,name))])),retained);assert.equal(readFileSync(join(root,'saves.jsonl'),'utf8').split('saveSucceeded').length-1,1);assert.equal(ledger.status(task.id).epoch,1);assert.equal(ledger.status(task.id).technical.status,'NOT_RUN');
  if(process.env.PHOTOCRAFT_CHECKPOINT_HARNESS_REPORT)writeFileSync(process.env.PHOTOCRAFT_CHECKPOINT_HARNESS_REPORT,JSON.stringify({schema:'photocraft-checkpoint-harness-evidence/v1',status:'PASS',originalTaskId:task.id,childTaskId:child.id,checkpointRecordSha256:checked.checkpoint.recordSha256,checkpointProjectSha256:checked.checkpoint.projectSha256,childProjectSha256:result.technical.projectSha256,originalIntentEpoch:1,originalFilesUnchanged:true,originalSaveCount:1,revisionCount:1,remainingRevisions:0,repeatedRecoverSameChild:true,foreignCheckpointRefused:true,foreignExitTokenRefused:true,checkpointMutationBeforeRunRefused:true,exhaustedBudgetRefused:true,typeLayerCount:1,creative:'NOT_RUN',sourceSha256:result.executionIdentity.sha256},null,2)+'\n');
 }finally{ledger.close();rmSync(root,{recursive:true,force:true});}
});
