import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,realpathSync,mkdirSync,writeFileSync,readFileSync,rmSync,statSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Ledger} from '../src/harness/ledger.ts';
import {Runner} from '../src/harness/runner.ts';
import {canonical,digest,fileDigest} from '../src/protocol/files.ts';
function fixture(){
 const root=realpathSync(mkdtempSync(join(tmpdir(),'photocraft-progress-observe-'))),ledger=new Ledger(join(root,'state'));
 const task=ledger.create({idempotencyKey:'original',brief:'observe original work',plan:{document:{width:64,height:64},operations:[]},output:join(root,'output'),authorization:{ref:'user',writeRoot:root},budget:{deadline:Date.now()+120000,maxRevisions:1,reserveBytes:0}}),epoch=ledger.claim(task.id);
 const skill=join(root,'skill');mkdirSync(join(skill,'scripts'),{recursive:true});mkdirSync(join(skill,'references'));writeFileSync(join(skill,'scripts/runtime.lock.json'),JSON.stringify({artifacts:{'darwin-arm64':{binarySha256:'9'.repeat(64)},'linux-x86_64':{binarySha256:'9'.repeat(64)}}}));const runner=new Runner(ledger,{skillRoot:skill,python:'python3'});const identity=runner.identity();ledger.update(task.id,epoch,current=>{current.executionIdentity=identity;current.worker={supervisor:true,token:'owned-token',childPid:null};});
 const context={plan:task.request.plan,executionIdentity:{planHash:digest(canonical(task.request.plan)),projectRevision:null,runtimeSha256:'9'.repeat(64),inputHashes:{}},taskBinding:{taskId:task.id,taskIdentity:task.identity,epoch,workerToken:'owned-token',sourceSha256:identity.sha256}};
 const path=join(root,'.photocraft-progress-'+digest(task.request.output)+'.json');mkdirSync(join(root,'stage'));const stageInfo=statSync(join(root,'stage'),{bigint:true});const record={stageIdentity:[String(stageInfo.dev),String(stageInfo.ino)],schema:'photocraft-progress/v1',targetHash:digest(task.request.output),sequence:1,ownerPid:process.pid,stage:'../stage',phase:'submitted',operations:[],completedOperations:0,replayAllowed:false,context};writeFileSync(path,canonical(record));
 const reply={schema:'photocraft-progress-inspection/v1',result:'PASS',recordSha256:fileDigest(path),record,stage:join(root,'stage'),stageAvailable:true,replayAllowed:false,technical:'NOT_RUN',creative:'NOT_RUN'};
 return {root,ledger,runner,task,path,reply,close(){ledger.close();rmSync(root,{recursive:true,force:true});}};
}
test('progress status rejects foreign producer and changing snapshots without mutating task or events',()=>{
 for(const kind of ['foreign','changed','malformed']){
  const f=fixture();try{
   const before=canonical(f.ledger.status(f.task.id)),events=canonical(f.ledger.db.prepare('SELECT * FROM events').all());
   if(kind==='foreign'){f.reply.record.context.taskBinding.workerToken='foreign';writeFileSync(f.path,canonical(f.reply.record));f.reply.recordSha256=fileDigest(f.path);}
   f.runner.python=()=>{if(kind==='changed')writeFileSync(f.path,'changed during read');return kind==='malformed'?{result:'PASS'}:f.reply;};
   const result=f.runner.status(f.task.id);assert.equal(result.progressObservation.status,'UNAVAILABLE');if(kind==='foreign')assert.match(result.progressObservation.code,/progress_task_binding_mismatch/);assert.equal(result.progressObservation.replayAllowed,false);assert.equal(result.technical.status,'NOT_RUN');assert.equal(canonical(f.ledger.status(f.task.id)),before);assert.equal(canonical(f.ledger.db.prepare('SELECT * FROM events').all()),events);
  }finally{f.close();}
 }
});

test('native hard worker kill keeps observed original progress without inventing a failure checkpoint',{skip:process.env.PHOTOCRAFT_NATIVE_TEST!=='1'},async()=>{
 const {chmodSync,existsSync}=await import('node:fs');const root=realpathSync(mkdtempSync(join(tmpdir(),'photocraft-native-progress-'))),ledger=new Ledger(join(root,'state'));let pending:Promise<any>|undefined;let workerPid:number|undefined;
 try{
  const realPython=process.env.PHOTOCRAFT_PYTHON??'/opt/anaconda3/bin/python3',source=process.env.PHOTOCRAFT_SOURCE_ROOT!,skillRoot=process.env.PHOTOCRAFT_SKILL_ROOT!,marker=join(root,'saved'),shim=join(root,'python-shim'),injection=join(source,'tests/fixtures/workflow_progress_pause.py');
  writeFileSync(shim,'#!'+realPython+'\nimport os,sys,runpy\nargs=sys.argv[1:]\nif len(args)>2 and args[2].endswith("workflow.py") and "--check" not in args:\n sys.argv=['+JSON.stringify(injection)+','+JSON.stringify(marker)+',args[2],*args[3:]]\n runpy.run_path('+JSON.stringify(injection)+',run_name="__main__")\nelse: os.execv('+JSON.stringify(realPython)+',['+JSON.stringify(realPython)+',*args])\n');chmodSync(shim,0o700);
  const runner=new Runner(ledger,{skillRoot,python:shim}),task=ledger.create({idempotencyKey:'original',brief:'observe interrupted original save',plan:{document:{width:64,height:64,background:'#ffffff'},operations:[{command:'type.create',params:{text:'KEEP',font:'Arial',size:12,x:8,y:20},as:'title'}],exports:[]},output:join(root,'output'),authorization:{ref:'user',writeRoot:root},budget:{deadline:Date.now()+120000,maxRevisions:1,reserveBytes:0}});
  pending=runner.run(task.id);const deadline=Date.now()+20000;while(!existsSync(marker)){if(Date.now()>deadline)throw new Error('native save window missing');await new Promise(resolve=>setTimeout(resolve,20));}
  const rows=canonical(ledger.db.prepare('SELECT * FROM tasks').all()),events=canonical(ledger.db.prepare('SELECT * FROM events').all());const live=runner.status(task.id);assert.equal(live.progressObservation.status,'OBSERVED');assert.equal(live.progressObservation.workerStoppedConfirmed,false);assert.equal(live.progressObservation.record.phase,'submitted');assert.equal(live.progressObservation.record.lastAttempt.tool,'doc_save');assert.equal(canonical(ledger.db.prepare('SELECT * FROM tasks').all()),rows);assert.equal(canonical(ledger.db.prepare('SELECT * FROM events').all()),events);
  const {spawnSync}=await import('node:child_process');const command=spawnSync(process.execPath,['src/cli.ts','status','--state-dir',ledger.root,'--task',task.id,'--skill-root',skillRoot,'--python',shim],{cwd:join(import.meta.dirname,'..'),encoding:'utf8',timeout:30000});assert.equal(command.status,0,command.stdout+command.stderr);assert.equal(JSON.parse(command.stdout).progressObservation.status,'OBSERVED');assert.equal(canonical(ledger.db.prepare('SELECT * FROM tasks').all()),rows);assert.equal(canonical(ledger.db.prepare('SELECT * FROM events').all()),events);
  const stage=live.progressObservation.stage,project=join(stage,'project.pcraft'),savedSha=fileDigest(project),progressPath=join(root,'.photocraft-progress-'+digest(task.request.output)+'.json'),progressBytes=readFileSync(progressPath);workerPid=live.progressObservation.record.ownerPid;process.kill(workerPid!,'SIGKILL');const result=await pending;
  assert.equal(result.state,'reconciling');assert.equal(result.workerExitReceipt.workflowPid,workerPid);assert.equal(result.workerExitReceipt.processGroupGone,true);const observed=runner.status(task.id);assert.equal(observed.progressObservation.workerStoppedConfirmed,true);assert.equal(observed.progressObservation.status,'OBSERVED');assert.ok(Number.isSafeInteger(observed.progressObservation.record.context.bindings.title.layer));assert.equal(observed.progressObservation.record.context.plan.operations[0].params.text,'KEEP');assert.equal(observed.technical.status,'NOT_RUN');assert.equal(observed.creative.status,'NOT_RUN');assert.equal(observed.checkpoint,undefined);assert.equal(existsSync(join(stage,'failure.json')),false);assert.equal(existsSync(join(task.request.output,'failure.json')),false);
  const reconciled=await runner.reconcile(task.id);assert.equal(reconciled.recoveryAction,'inspect_interrupted_stage');assert.equal(reconciled.checkpoint,undefined);assert.equal(reconciled.epoch,1);assert.equal(reconciled.revisions,0);assert.equal(ledger.db.prepare('SELECT count(*) AS n FROM tasks').get().n,1);assert.deepEqual(readFileSync(progressPath),progressBytes);assert.equal(fileDigest(project),savedSha);await assert.rejects(()=>runner.run(task.id),/reconcile_required/);
  if(process.env.PHOTOCRAFT_PROGRESS_HARNESS_REPORT)writeFileSync(process.env.PHOTOCRAFT_PROGRESS_HARNESS_REPORT,JSON.stringify({schema:'photocraft-progress-harness-native/v1',status:'PASS',taskId:task.id,taskIdentity:task.identity,sourceSha256:result.executionIdentity.sha256,progressRecordSha256:fileDigest(progressPath),savedProjectSha256:savedSha,phase:reconciled.progressObservation.record.phase,lastAttempt:reconciled.progressObservation.record.lastAttempt,originalEpoch:1,originalFilesUnchanged:true,liveStatusReadOnly:true,workerStoppedConfirmed:true,failureRecordInvented:false,checkpointInvented:false,replayRefused:true,technical:'NOT_RUN',creative:'NOT_RUN',scope:'Actual saved native and hard workflow SIGKILL; original progress observed, explicit checkpoint recovery remains open.'},null,2)+'\n');
 }finally{if(pending){const rows=ledger.db.prepare('SELECT id FROM tasks').all() as any[];for(const row of rows)try{ledger.stop(row.id);}catch{}try{await pending;}catch{}}ledger.close();rmSync(root,{recursive:true,force:true});}
});
